apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-helm-bg
  annotations:
    kargo.akuity.io/color: red
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: helm-guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars: 
      - name: app
        value: blue-green
      - name: image
        value: guestbook
      steps: 
      - task: 
          name: standard-process-helm-bg
--- 
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-helm-bg
  annotations:
    kargo.akuity.io/color: yellow
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: helm-guestbook
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars: 
      - name: app
        value: blue-green
      - name: image
        value: guestbook
      steps: 
      - task: 
          name: standard-process-helm-bg
  verification:
    analysisTemplates:
    - name: guestbook-verification-3
--- 
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-useast
  namespace: kargo-helm-bg
  annotations:
    kargo.akuity.io/color: green
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: helm-guestbook
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars: 
      - name: app
        value: blue-green
      - name: image
        value: guestbook
      steps: 
      - task: 
          name: standard-process-helm-bg
--- 
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-uswest
  namespace: kargo-helm-bg
  annotations:
    kargo.akuity.io/color: blue
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: helm-guestbook
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars: 
      - name: app
        value: blue-green
      - name: image
        value: guestbook
      steps: 
      - uses: git-clone
        config:
          repoURL: https://github.com/emilyxinyi/kargo-helm-bg.git
          checkout:
          - branch: main
            path: ./src
          - branch: stage/${{ ctx.stage }}
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: yaml-update
        as: update-image
        config: 
          path: ./src/${{ vars.app }}/values.yaml
          updates: 
          - key: image.tag
            value: ${{ imageFrom("ghcr.io/emilyxinyi/guestbook", warehouse("helm-guestbook")).Tag }}
      - uses: copy
        config:
          inPath: ./src
          outPath: ./out
      # Commit the changes to the Git repository.
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      # Push the changes to the Git repository.
      - uses: git-push
        as: push
        config:
          path: ./out
          generateTargetBranch: true
      - uses: git-open-pr
        as: open-pr
        config:
          repoURL: https://github.com/emilyxinyi/kargo-helm-bg.git
          createTargetBranch: true
          sourceBranch: ${{ outputs.push.branch }}
          targetBranch: stage/prod-uswest
      - uses: git-wait-for-pr
        as: wait-for-pr
        config:
          repoURL: https://github.com/emilyxinyi/kargo-helm-bg.git
          prNumber: ${{ outputs['open-pr'].prNumber }}
      - uses: compose-output
        as: commit-link
        config:
          url: https://github.com/emilyxinyi/kargo-helm-bg/commit/${{ outputs['wait-for-pr'].commit }}
      - uses: argocd-update 
        config:
          apps:
          - name: kargo-helm-bg-${{ ctx.stage }}
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-helm-bg.git